package com.recoverx.dto;

import java.util.List;

/**
 * Returned by POST /api/recovery/process/{externalId}.
 * auditLines are the stage-tagged lines generated by THIS call (e.g. "[DETECT] ...",
 * "[DIAGNOSE] ..."), in order, so the frontend can replay them against the
 * pipeline animation exactly as the backend produced them.
 */
public record ProcessResultDTO(
        TransactionDTO transaction,
        DecisionDTO decision,
        List<String> auditLines,
        boolean resolved
) {
}
